---
name: CGI-Application-Plugin-FormState
version: 0.01
author:
  - Michael Graham <mag-perl@occamstoothbrush.com>
abstract: Store Form State without Hidden Fields
license: perl
requires:
  CGI::Application::Plugin::Session: 0.09
  CGI::Session: 4
  Test::More: 0
provides:
  CGI::Application::Plugin::FormState:
    file: lib/CGI/Application/Plugin/FormState.pm
    version: 0.01
generated_by: Module::Build version 0.2611
